= Neo4j - Tableau Integration

== Neo4j Tableau Web Data Connector

The Web Data Connector requires a hosted HTML page to pass the query to Neo4j and return the results directly to Tableau using JavaScript.

There is a sample HTML page in the `website` directory that will allow you to get started.

*The link:./documentation/neo4j-tableau-web-data-connector.adoc[documentation] details installation, usage and configuration of the Connector.*

There are also a separate installation instructions for 
link:./documentation/installation/WindowsInstallationDirections.txt[Windows], 
link:./documentation/installation/MacInstallationDirections.txt[Mac] and 
link:./documentation/installation/UnixInstallationDirections.txt[Unix].

=== Example Queries

There are sample queries in the link:./documentation/sample_queries.txt[sample_queries.txt] file.

=== TDE File Generator Extension

To create a TDE from the results of a Neo4j Cypher query, pass for instance the following query:

[source,cypher]
----
Match (n:Movie) return n
----

To this URL:

http://localhost:7474/export/tableau/tde/Match%20(n%3AMovie)%20return%20n

It will generate and return a TDE file for usage in Tableau.

== Versions

This code has been tested on Neo4j 2.2 and 2.3 versions. 
This code has been tested against Tableau 9.1.
The TDE format should be able to be read by Tableau versions 7 and higher.
